[package]
edition = "2021"
name = "lapjv"
version = "0.2.1"
authors = ["Andrii Dmytrenko <andrii.dmytrenko@deliveroo.co.uk>"]
description = "Linear Assignmment Problem solve using Jonker-Volgenant algorithm"
license = "MIT"
documentation = "https://docs.rs/lapjv"
homepage = "https://github.com/Antti/lapjv-rust"
repository = "https://github.com/Antti/lapjv-rust.git"

include = ["**/*.rs", "Cargo.toml", "README.md"]

[badges]
travis-ci = { repository = "Antti/lapjv-rust", branch = "master" }
maintenance = { status = "as-is" }

[dependencies]
log = "0.4.26"
nalgebra = "0.33.2"
num-traits = "0.2.19"
rand = "0.9.0"
